version: '3'

services:
  ldap:
     image: osixia/openldap:1.4.0
     container_name: ldap
     hostname: local.com
     environment:
       - LDAP_TLS_VERIFY_CLIENT=try
       - LDAP_OPENLDAP_UID=1000
       - LDAP_OPENLDAP_GID=1000
       - LDAP_ORGANISATION="Local"
       - LDAP_DOMAIN="local.com"
       - LDAP_ADMIN_PASSWORD="secret"
     ports:
       - "389:389"
       - "636:636"
